export const navlinks = [
  { path: "/", text: "home" },
  { path: "/about", text: "about" },
  { path: "/resume", text: "resume" },
  {
    path: "/portfolio",
    text: "portfolio",
    // submenu: true,
    sublink: [
      { path: "/moodboard", text: "moodboard" },
      { path: "/color-pallete", text: "color pallete" },
      { path: "/fabric-board", text: "fabric board" },
      { path: "/flats", text: "flats" },
      { path: "/croquis", text: "croquis" },
      { path: "/style-board", text: "style board" },
      { path: "/design-brief", text: "design brief" },
      { path: "/working-sketches", text: " working sketches" },
      { path: "/design-specifications", text: "design specifications" },
      { path: "/cutting-of-fabrics", text: "cutting of fabrics" },
      { path: "/fabric-board", text: "fabric board" },
      { path: "/final-work", text: "final work" },
      { path: "/cost-sheet", text: "cost sheet" },
      { path: "/accessories", text: "accessories" },
      { path: "/embroidery-applique", text: "Embroidery/Applique " },
      { path: "/textiles-work", text: "textiles work" },
      { path: "/beads-works", text: "beads works" },
    ],
  },
  { path: "/contact", text: "contact" },
];
